
version: '3.8'

services:

  redis:
    image: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo
    ports:
      - 27017:27017

  mailcatcher:
    image: stpaquet/alpinemailcatcher
    ports:
      - 1080:1080
      - 1025:1025

  # spammer:
  #   image: bhurlow/spammer
  #   scale: 3

  # logger:
    # build: .
    # ports:
      # - 8080:2387
    # environment:
      # NODE_ENV: ''
    # restart: always
    # command: -c /conf.toml
    # volumes:
      # - "/var/run/docker.sock:/var/run/docker.sock"
      # - .:/app
      # - ./conf.toml:/conf.toml